### ISSUE TITLE
let comments be collapsible?

### ISSUE THREAD

**Issue by xxredxpandaxx** [NighthawkSLO/language-rainmeter#10]
any chance you make comments be able to collapse an entire section? I find it easier to organize the code that way. Also love the syntax so far, can't find anything wrong with it.

e.g.
;---CPU
  ;---core1
    [Meter1]

Could be 
;---CPU
  ;---core1

Or
;---CPU

**Comment by avernan** [comment]
Try giving a look at [custom-folds](https://atom.io/packages/custom-folds). I find it particularly convenient in grouping/collapsing a set of sections.
I personally changed the beginning and end of foldable regions to "{{{" and "}}}" respectively. This makes it quicker to type, but a bit awkward because of the parentheses autocomplete

**Comment by marcopixel** [comment]
Atom needs an closing tag to properly generate folds and this is not possible with Rainmeter's ini files.

As for the comments, it is currently already possible to fold them because of changes to Atom since this issue was posted. If you really want to have folds for the different sections, i would recommend using [custom-folds](https://atom.io/packages/custom-folds) as you can pretty much set the fold wherever you want.
